[sandbox_workspace_write]
exclude_tmpdir_env_var = false  # Allow $TMPDIR
exclude_slash_tmp = false       # Allow /tmp
network_access = true
writable_roots = ["/Users/rwilton/.pyenv/shims", "/Users/rwilton/Library/Caches/"]
